version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile 
    image: my-nginx-proxy 
    container_name: nginx
    restart: always
    ports:
      - "8080:80" 
    depends_on:
      - node_app 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  node_app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: my-node-app
    container_name: node_app
    restart: always
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: nodedb
    depends_on:
      - mysql 
    volumes:
      - ./node:/usr/src/app 
      - /usr/src/app/node_modules 

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: nodedb 
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: